### ISSUE TITLE
请问有兴趣共同探讨中文编程相关话题吗?

### ISSUE THREAD

**Issue by nobodxbodon** [itorr/templet#1]
[v2帖](https://www.v2ex.com/t/498973#r_6320901)介绍至此, 不知对使用中文命名还有兴趣吗?

**Comment by itorr** [comment]
有兴趣呀，之前搞过这个来着🤣 http://front.dog/e

**Comment by nobodxbodon** [comment]
之前就看到了.
组里有几位在实践中文命名的(Java/Python/JS等), 也有几位尝试中文语法编程语言的. 欢迎串门.
